# tomcat
server:
  port: 8081
# spring boot admin
spring:
  application:
    name: mango-backup
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mango?useUnicode=true&zeroDataTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    userName: root
    password: ddx19920930
  boot:
    admin:
      client:
        url: http://localhost:8082
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        instance-id: ${spring.application.name}:${server.port}

#开放健康检查接口
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# backup datasource
mango:
  backup:
    datasource:
      host: localhost
      userName: root
      password: ddx19920930
      database: mango