# tomcat
server:
  port: 8082
# spring boot admin
spring:
  application:
    name: mango-monitor
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mango?useUnicode=true&zeroDataTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    userName: root
    password: ddx19920930
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        #serviceName: ${spring.application.name}
        instance-id: ${spring.application.name}:${server.port}